set search_path = project3;

set search_path = project3;
create schema project3;


create table sensor
(
    id         integer generated by default as identity
        primary key,
    name       varchar(200) not null
        unique,
    created_at timestamp    not null
);
create table measurement
(
    id         integer generated by default as identity
        primary key,
    value      integer   not null
        constraint measurement_value_check
            check (value >= '-100'::integer)
    constraint measurement_value_check1
        check (value <= 100),
is_rainy   boolean   not null,
sensor_id  integer
                     references sensor
                         on update cascade on delete set null,
created_at timestamp not null
);
